# Generated by Django 5.0.2 on 2024-05-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlemap_reviews', '0002_alter_keywordreviews_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='abc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=4, verbose_name='店內代號')),
                ('date', models.DateField(verbose_name='評論日期')),
                ('keywords', models.CharField(max_length=12, verbose_name='關鍵字')),
                ('keywordCount', models.IntegerField(verbose_name='關鍵字次數')),
                ('category', models.BooleanField(choices=[(1, '好評'), (2, '負評')], verbose_name='類別')),
            ],
            options={
                'db_table': 'abc',
            },
        ),
    ]
