# Generated by Django 5.0.2 on 2024-05-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlemap_reviews', '0003_abc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=100, null=True)),
                ('place_name', models.CharField(max_length=100, null=True)),
                ('user_name', models.CharField(max_length=100, null=True)),
                ('rating', models.IntegerField(null=True)),
                ('other_ratings', models.CharField(max_length=255, null=True)),
                ('review_text', models.TextField(null=True)),
                ('published_date', models.DateField(null=True)),
                ('response_from_owner_text', models.TextField(null=True)),
                ('response_from_owner_ago', models.CharField(max_length=100, null=True)),
                ('response_from_owner_date', models.DateField(null=True)),
                ('review_likes_count', models.IntegerField(null=True)),
                ('total_number_of_reviews_by_reviewer', models.IntegerField(null=True)),
                ('total_number_of_photos_by_reviewer', models.IntegerField(null=True)),
                ('is_local_guide', models.BooleanField(null=True)),
                ('review_translated_text', models.TextField(null=True)),
                ('response_from_owner_translated_text', models.TextField(null=True)),
            ],
            options={
                'db_table': 'shop_reviews',
            },
        ),
        migrations.DeleteModel(
            name='abc',
        ),
    ]
