# Generated by Django 5.0.2 on 2024-05-10 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googlemap_reviews', '0004_shopreviews_delete_abc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keywordreviews',
            old_name='store',
            new_name='store_id',
        ),
    ]
