# Generated by Django 5.0.2 on 2024-05-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlemap_reviews', '0006_alter_keywordreviews_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=50)),
                ('store_name', models.CharField(max_length=50)),
            ],
        ),
    ]
