# Generated by Django 5.0.2 on 2024-05-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlemap_reviews', '0007_storelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordreviews',
            name='store_id',
            field=models.CharField(max_length=20, verbose_name='店內代號'),
        ),
    ]
