# Generated by Django 5.0.3 on 2024-05-30 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googlemap_reviews', '0009_storelist_place_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keywordreviews',
            old_name='store_id',
            new_name='place_name',
        ),
        migrations.RemoveField(
            model_name='storelist',
            name='store_id',
        ),
    ]
